apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: quorum-worker
        image: pradhanaren/quorum:worker-distroless
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "256m"
          limits:
            memory: "128Mi"
            cpu: "512m"
        envFrom:
          - configMapRef:
              name: backend-cm
          - secretRef:
              name: db-creds
