apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce