apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    app: redis
spec:
  serviceName: "redis-svc"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: quorum-redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - name: redis
          containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "256m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
